### PR TITLE
Stop extending String

### PR DESCRIPTION
**Pull request by nateberkopec**
[This is causing issues for users of Rails](https://github.com/rails/rails/issues/17656).

### CODE REVIEW

**Comment by jnraine** [comment]
I ran into this issue as well. A few gems we use depend on terminal-table. 

@tj, what are your thoughts on removing the monkey-patch to `String`?

**Comment by naiyt** [comment]
Has there been any consideration into merging this? I've also run into this issue.

**Comment by tj** [comment]
sounds good to me, I haven't touched Ruby in years though, anyone want to maintain?

**Comment by nateberkopec** [comment]
@tj sure. my email address is on my github profile.

**Comment by tj** [comment]
@nateberkopec added!

**Comment by naiyt** [comment]
Excellent, thanks @nateberkopec and @tj!

**Comment by naiyt** [comment]
Would one of you be able to push a new version of terminal-table to RubyGems? It's a dependency for other gems we are using, which makes it a bit awkward to get them on the new version.

**Comment by nateberkopec** [comment]
As soon as @tj adds me on rubygems, or does it himself, that will happen.

**Pull request merged**
