### PR TITLE
add support for cjk character

### PR DESCRIPTION
**Pull request by fireinice**
some east asian characters (chiness, japanese, korean aka cjk) will occupied two char widths compared with ascii. and will lead to indent errors. this commit will consider the character set when caculate the alighnment.

### CODE REVIEW

**Comment by fireinice** [comment]
I will write some characters for example. 

中国
1234

**Comment by nateberkopec** [comment]
It looks like this needs to rebased against the latest master.

**Comment by nateberkopec** [comment]
I cannot accept any pull requests that extend String - please find another way to accomplish what you're trying to do here! :grin:

**Comment by fireinice** [comment]
and this would need ruby version 1.9 at least, I can not find a clean way to support 1.8 . if I could find other ways for string thing. will this gem conside dropping ruby 1.8 supports?

**Comment by nateberkopec** [comment]
String encoding changed a lot with 1.9. I'm not sure yet. My first priority is to get a bugfix release out the door (waiting on a gem push/gem ownership change from @tj), then I'll be able to work on merging this and considering ruby version support going forward.

**Comment by sodabrew** [comment]
@fireinice If you correctly specify the encoding, does Ruby understand that the CJK string's length is shorter than its bytesize?

Because of Encoding, this has been true for a few years now:
In Ruby 1.8, String#size == String#length == String#bytesize
In Ruby 1.9+, String#size == String#length <= String#bytesize (depending on encoding).

**Pull request closed without merging**
