### PR TITLE
Tons of fixes, implemented column wrap

### PR DESCRIPTION
**Pull request by terabyte**
hey man, I saw there have been lots of pull requests and none have been accepted.  If this gem has been abandoned, I'd be glad to take it over for you.  I have a project I'd like to release that depends upon these changes I (and yzhou7) have made.  Let me know if this is ok, or if you want some changes.  Otherwise, if the gem is dead, maybe I'll just fork it.

I have found this gem you wrote VERY useful and greatly appreciate it.

Please let me know either way... Thanks!

### CODE REVIEW

**Comment by nateberkopec** [comment]
Hey man - I'm going to need a little more time to review this, but can you please remove the gem version bump from this PR?

**Comment by bogdanRada** [comment]
+1

**Comment by nateberkopec** [comment]
This PR has a few issues.

a) Needs a rebase,
b) I think you're just adding on a big column width adjustment method without removing/modifying any of the existing column width calculating code. Aren't we calculating the column widths twice, then?
c) No tests for column wrapping (just raising an error).
d) Gem version bump, which should be removed.

**Comment by terabyte** [comment]
When I find a chance, I will try to look at this again and refresh it.  I haven't thought about this code in like 2 years, so it's probably going to take me a bit to figure it out =)

**Comment by nateberkopec** [comment]
@terabyte No problem mate. Just taking over the management here, so there's lots of things to sweep up :)

**Comment by bogdanRada** [comment]
why was this closed? Is this never going to get merged ? I have a project that depends on this gem: https://github.com/bogdanRada/capistrano_multiconfig_parallel and i would really hate to have to use another solution . 

If the project is no longer maintained or dead please let me know. I would be glad to contribute to this gem development.

**Comment by nateberkopec** [comment]
No activity for 6 months and no commits for... 3 years. If this feature is important to you, please open another PR, which I will be happy to merge.

**Comment by nateberkopec** [comment]
To be clear, I maintain this project and just released a new version (1.6.0) today.

**Comment by bogdanRada** [comment]
thanks for the prompt response :) Glad to hear this is still maintained :D

**Comment by terabyte** [comment]
I'm glad to hear it too!  I'm sorry I never had time to rework this PR into something sane (and I agree it isn't really appropriate to merge it in the condition it was received).

For now, my tool can depend upon my "fork" (github.com/terabyte/terminal-table) directly from its gemfile, and hopefully some day I will move it over to the "real" terminal-table (better-implementing any features I need if they are still missing - they may even be present by now).

**Comment by terabyte** [comment]
(the responsibility for this "fork" happening is completely on me for being unresponsive in the past, and not caring / having time in the present)

**Pull request closed without merging**
