### PR TITLE
Added margin_left style

### PR DESCRIPTION
**Pull request by erwanlr**
Possibility to add a left margin, default ''

### CODE REVIEW

**Comment by nateberkopec** [comment]
Can you rebase this with master to fix your whitespace formatting issues?

**Comment by erwanlr** [comment]
Merged with the current master :)

Furthermore, it would be recommended to update the .rvmrc which ask for ruby 1.8.7 :O

Maybe also setup Travis to track builds/PR introducing issues and use rubocop for code style ? (I know, that's a lot, but it can also do good ;))

**Comment by nateberkopec** [comment]
Yeah we should just delete the .rvmrc.

I can't setup Travis because @tj owns the repo (and I think would have to create an organization in order to give me those privileges?) though I agree it would be valuable. So chalk that up as unlikely, unfortunately.

**Comment by nateberkopec** [comment]
Thanks for contributing :dancers:

**Pull request merged**
